from pathlib import Path
from html import escape
import json
r=Path(__file__).resolve().parent.parent
name='Joyce Ndehi & Company Advocates'
phone='0706 806 549'
wa='https://wa.me/254706806549'
email='joycendehiadvocates@gmail.com'
address='Telcom Exchange House, Biashara Street, 1st Floor, Kiambu Town, Kenya'
nav=[('Home','/'),('About Us','/about'),('Practice Areas','/practice-areas'),('Our Advocate','/managing-partner'),('Insights','/insights'),('Contact','/contact')]
icons={
 'arrow':'<path d="M4 12h16m-7-7 7 7-7 7"/>',
 'arrow-up':'<path d="M5 19 19 5M7 5h12v12"/>',
 'balance':'<path d="M12 3v18M5 21h14M4 7h16M6 7l-4 6h8L6 7Zm12 0-4 6h8l-4-6Z"/>',
 'home':'<path d="m3 11 9-8 9 8v10H3V11Z"/><path d="M9 21v-7h6v7"/>',
 'family':'<circle cx="8" cy="7" r="2"/><circle cx="17" cy="8" r="2"/><path d="M3 21v-5a5 5 0 0 1 10 0v5m1-8a4 4 0 0 1 7 3v5"/>',
 'briefcase':'<rect x="3" y="7" width="18" height="14" rx="2"/><path d="M8 7V5a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2M3 12c6 4 12 4 18 0"/>',
 'shield':'<path d="M12 2 4 5v6c0 5 3 8 8 11 5-3 8-6 8-11V5l-8-3Z"/><path d="m9 12 2 2 4-4"/>',
 'gavel':'<path d="m4 20 7-7m-5-5 5 5m-4-8 4-4 8 8-4 4-8-8Zm5 11 4-4 4 4-4 4-4-4Z"/>',
 'clock':'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l4 2"/>',
 'location':'<path d="M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 0 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/>',
 'phone':'<path d="M4 3h4l2 5-2.4 2a15 15 0 0 0 6.4 6.4l2-2.4 5 2v4a2 2 0 0 1-2 2A17 17 0 0 1 2 5a2 2 0 0 1 2-2Z"/>',
 'mail':'<rect x="2" y="5" width="20" height="14" rx="2"/><path d="m3 7 9 7 9-7"/>',
 'check':'<path d="m4 12 5 5L20 6"/>',
 'book':'<path d="M4 3h12a4 4 0 0 1 4 4v14H8a4 4 0 0 0-4-4V3Zm0 14a4 4 0 0 1 4-4h12"/>',
 'spark':'<path d="m12 2 2.5 7.5L22 12l-7.5 2.5L12 22l-2.5-7.5L2 12l7.5-2.5L12 2Z"/>',
 'menu':'<path d="M4 7h16M4 12h16M4 17h16"/>',
 'x':'<path d="M6 6l12 12M18 6 6 18"/>',
 'whatsapp':'<path d="M20.3 11.8a8.3 8.3 0 0 1-12.4 7.3L3 20.6l1.6-4.9a8.3 8.3 0 1 1 15.7-3.9Z"/><path d="M8.3 8.7c.9 3.1 3.3 5.5 6.4 6.5.6.2 1.3-.1 1.7-.6"/>',
}
def icon(key,cls='',size=24):return f'<svg class="{cls}" width="{size}" height="{size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.55" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">{icons[key]}</svg>'
def link(text,url,sty='btn btn-primary',key='arrow-up',extra=''):
 return f'<a href="{url}" class="{sty}" {extra}><span>{text}</span>{icon(key)}</a>'
def header(active):
 opts=''.join(f'<a href="{u}" class="{"active" if active==u else ""}" {"aria-current=\"page\"" if active==u else ""}>{n}</a>' for n,u in nav)
 return f'''<div class="utility-bar"><div class="container utility-inner"><span>{icon('location',size=13)} Kiambu Town, Kenya</span><div><a href="tel:+254706806549">{icon('phone',size=13)} {phone}</a><span class="utility-divider"></span><a href="mailto:{email}">{icon('mail',size=13)} {email}</a></div></div></div>
<header class="site-header" id="site-header"><div class="container header-inner"><a class="brand" href="/" aria-label="Joyce Ndehi and Company Advocates - home"><span class="brand-logo-disc"><img src="/images/logo-red.png" alt="Joyce Ndehi & Company Advocates logo" width="64" height="64"></span><span class="brand-type"><strong>Joyce Ndehi</strong><span>&amp; Company Advocates</span></span></a><nav class="desktop-nav" aria-label="Main navigation">{opts}</nav><a class="header-cta" href="/contact">Let's Talk {icon('arrow-up',size=17)}</a><button class="menu-toggle" type="button" aria-label="Open navigation" aria-controls="mobile-menu" aria-expanded="false">{icon('menu',size=24)}{icon('x','close-icon',size=24)}</button></div><nav id="mobile-menu" class="mobile-nav" aria-label="Mobile navigation" inert>{opts}<a class="mobile-contact" href="/contact">Request a consultation {icon('arrow')}</a></nav></header>'''
def footer():
 return f'''<section class="prefooter"><div class="container prefooter-inner"><div><span class="eyebrow eyebrow-light">YOUR NEXT STEP</span><h2>Let's find a way <em>forward.</em></h2><p>Begin with a conversation about your legal matter.</p></div>{link('Get in touch','/contact','btn btn-cream')}</div></section>
<footer class="site-footer"><div class="container"><div class="footer-grid"><div class="footer-about"><div class="footer-identity"><img src="/images/logo-white.png" width="76" height="76" alt=""><span><strong>Joyce Ndehi</strong><small>&amp; Company Advocates</small></span></div><p>Independent legal counsel in Kiambu Town. Practical advice, thoughtful representation and constructive paths to resolution.</p><div class="footer-social"><a href="{wa}" target="_blank" rel="noopener noreferrer" aria-label="Chat on WhatsApp">{icon('whatsapp')}</a><a href="mailto:{email}" aria-label="Email the firm">{icon('mail')}</a><a href="tel:+254706806549" aria-label="Call the firm">{icon('phone')}</a></div></div><div><h3>Explore</h3><a href="/about">About the firm</a><a href="/practice-areas">Practice areas</a><a href="/managing-partner">Meet Joyce Ndehi</a><a href="/insights">Legal insights</a></div><div><h3>Our work</h3><a href="/practice-areas#mediation">Mediation &amp; ADR</a><a href="/practice-areas#succession">Succession &amp; probate</a><a href="/practice-areas#property">Property &amp; conveyancing</a><a href="/practice-areas#commercial">Commercial &amp; corporate</a></div><div class="footer-contact"><h3>Find us</h3><p>Telcom Exchange House<br>Biashara Street, 1st Floor<br>Kiambu Town, Kenya</p><a href="tel:+254706806549">{phone}</a><a href="mailto:{email}">{email}</a></div></div><div class="footer-bottom"><span>© 2026 Joyce Ndehi &amp; Company Advocates. All rights reserved.</span><div><a href="/privacy">Privacy</a><a href="/terms">Terms</a><span>Website information is general, not legal advice.</span></div></div></div></footer>
<a class="whatsapp-fab" href="{wa}" target="_blank" rel="noopener noreferrer" aria-label="Chat with Joyce Ndehi &amp; Company Advocates on WhatsApp" title="Chat on WhatsApp"><svg viewBox="0 0 32 32" width="31" height="31" aria-hidden="true" focusable="false" xmlns="http://www.w3.org/2000/svg"><path fill="currentColor" d="M16 .8A15.15 15.15 0 0 0 2.9 23.54L.8 31.2l7.84-2.06A15.2 15.2 0 1 0 16 .8Zm0 27.64a12.4 12.4 0 0 1-6.3-1.72l-.46-.27-4.66 1.22 1.24-4.55-.3-.47a12.4 12.4 0 1 1 10.48 5.79Zm6.84-9.3c-.37-.19-2.21-1.09-2.55-1.21s-.59-.19-.83.19-.96 1.21-1.18 1.46-.43.28-.8.09a10.2 10.2 0 0 1-3-1.85 11.2 11.2 0 0 1-2.07-2.58c-.22-.37-.02-.57.17-.76.17-.16.37-.43.55-.64.19-.22.25-.37.37-.62.12-.25.06-.46-.03-.64-.09-.19-.84-2-1.14-2.73-.3-.72-.61-.62-.84-.63h-.72c-.25 0-.65.09-.99.46s-1.3 1.27-1.3 3.1 1.33 3.6 1.52 3.84 2.62 4.03 6.36 5.64c.89.39 1.59.62 2.13.8.9.28 1.72.24 2.37.15.72-.11 2.2-.9 2.52-1.77.31-.87.31-1.62.22-1.77-.1-.16-.34-.25-.71-.43Z"/></svg></a>
<script src="/assets/js/site.js?v=10" defer></script>'''
site_url='https://joyce-ndehi-company-advocates.vercel.app'
site_image=site_url+'/images/joyce-ndehi-social-card.webp'
site_icon=site_url+'/images/icon-512.png'
page_labels={'about':'About Us','practice-areas':'Practice Areas','managing-partner':'Our Advocate','insights':'Legal Insights','contact':'Contact','privacy':'Privacy Policy','terms':'Terms of Use'}

def wrap(title,desc,body,active='/',slug=''):
 canonical=site_url+('/'+slug if slug else '/')
 encoded_title=escape(title);encoded_desc=escape(desc,quote=True)
 # Retain the existing clean URL structure, and make social previews route-specific.
 hero=not slug and title.startswith('Joyce Ndehi & Company Advocates |')
 preload='<link rel="preload" as="image" href="/assets/images/legal-hero.jpg" fetchpriority="high">' if hero else ''
 error_page=title.split(' |',1)[0] in ('404','500','503','504')
 organization={"@type":"LegalService","@id":site_url+"/#firm","name":name,"url":site_url+"/","logo":site_icon,"image":site_image,"description":"Independent legal advice, mediation, succession, property, commercial and dispute resolution services in Kiambu Town, Kenya.","telephone":"+254706806549","email":email,"address":{"@type":"PostalAddress","streetAddress":"Telcom Exchange House, Biashara Street, 1st Floor","addressLocality":"Kiambu","addressRegion":"Kiambu County","addressCountry":"KE"},"areaServed":{"@type":"AdministrativeArea","name":"Kiambu County, Kenya"},"hasMap":"https://www.google.com/maps/search/?api=1&query=Telcom+Exchange+House+Biashara+Street+Kiambu+Town+Kenya","contactPoint":{"@type":"ContactPoint","contactType":"customer service","telephone":"+254706806549","email":email,"availableLanguage":["en"]},"knowsAbout":["Mediation and alternative dispute resolution","Succession and probate","Property and conveyancing","Commercial and corporate law","Data protection and intellectual property","Litigation and legal advisory"]}
 web_site={"@type":"WebSite","@id":site_url+"/#website","url":site_url+"/","name":name,"publisher":{"@id":site_url+"/#firm"},"inLanguage":"en-KE"}
 web_page={"@type":"WebPage","@id":canonical+"#webpage","url":canonical,"name":title,"description":desc,"isPartOf":{"@id":site_url+"/#website"},"about":{"@id":site_url+"/#firm"},"inLanguage":"en-KE","primaryImageOfPage":{"@type":"ImageObject","url":site_image,"width":1200,"height":630}}
 graph=[organization,web_site,web_page]
 if slug and not error_page:
  graph.append({"@type":"BreadcrumbList","@id":canonical+"#breadcrumbs","itemListElement":[{"@type":"ListItem","position":1,"name":"Home","item":site_url+"/"},{"@type":"ListItem","position":2,"name":page_labels.get(slug,title.split('|')[0].strip()),"item":canonical}]})
 if error_page:
  # Error content is never a search result, regardless of its HTTP response status.
  robots='<meta name="robots" content="noindex,follow">'
 else: robots='<meta name="robots" content="index,follow,max-image-preview:large">'
 structured_data=json.dumps({"@context":"https://schema.org","@graph":graph},ensure_ascii=False,separators=(',',':')).replace('<','\\u003c')
 return f'''<!doctype html><html lang="en-KE"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#cf0000"><title>{encoded_title}</title><meta name="description" content="{encoded_desc}">{robots}<link rel="canonical" href="{canonical}"><link rel="icon" type="image/png" sizes="192x192" href="/images/icon-192.png"><link rel="apple-touch-icon" href="/images/icon-192.png"><link rel="manifest" href="/site.webmanifest"><meta property="og:type" content="website"><meta property="og:site_name" content="{name}"><meta property="og:locale" content="en_KE"><meta property="og:title" content="{encoded_title}"><meta property="og:description" content="{encoded_desc}"><meta property="og:url" content="{canonical}"><meta property="og:image" content="{site_image}"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="Joyce Ndehi &amp; Company Advocates, Kiambu"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="{encoded_title}"><meta name="twitter:description" content="{encoded_desc}"><meta name="twitter:image" content="{site_image}">{preload}<link rel="stylesheet" href="/assets/css/site.css?v=10"><script type="application/ld+json">{structured_data}</script></head><body><a class="skip-link" href="#main-content">Skip to content</a>{header(active)}<main id="main-content">{body}</main>{footer()}</body></html>'''

def eyebrow(text,light=False):return f'<span class="eyebrow {"eyebrow-light" if light else ""}">{text}</span>'
def section_header(kicker,title,desc='',right=''):
 return f'<div class="section-heading"><div>{eyebrow(kicker)}<h2>{title}</h2></div><div class="section-heading-side">{f"<p>{desc}</p>" if desc else ""}{right}</div></div>'
services=[
 ('mediation','01','Mediation & ADR','A constructive way through complex disagreements.','balance','Confidential resolution for family, workplace, commercial and property matters.'),
 ('succession','02','Succession & Probate','Care and clarity for matters of inheritance.','family','Wills, estate administration, probate and succession disputes.'),
 ('property','03','Property & Conveyancing','Know where you stand before you sign.','home','Due diligence, transfers, ownership questions and property transactions.'),
 ('commercial','04','Commercial & Corporate','Sound decisions begin with sound advice.','briefcase','Contracts, business matters, corporate and tax-related advisory support.'),
 ('data','05','Data Protection & IP','Protect what you create and what you hold.','shield','Data-protection obligations, copyright and intellectual-property advice.'),
 ('litigation','06','Litigation & Advisory','Considered strategy when a matter needs action.','gavel','Drafting, negotiation, legal representation and dispute strategy.')]
def service_cards():
 out=''
 for slug,n,t,h,i,desc in services:
  image='/assets/images/'+{'mediation':'mediation-discussion.jpg','succession':'succession-family.jpg','property':'property-keys.jpg','commercial':'commercial-contract.jpg','data':'data-protection.jpg','litigation':'litigation-justice.jpg'}[slug]
  out+=f'<a class="service-card" href="/practice-areas#{slug}"><div class="service-picture"><img src="{image}" alt="{t} — illustrative photograph" loading="lazy" width="900" height="600"><span class="service-no">{n} / 06</span></div><div class="service-content"><span class="service-icon">{icon(i,size=25)}</span><h3>{t}</h3><p>{desc}</p><span class="service-explore">Learn more {icon("arrow-up",size=18)}</span></div></a>'
 return out
insights=[('Mediation','When mediation may be worth considering','A confidential setting for discussing disputes and exploring workable outcomes.','mediation'),('Succession','Succession planning and estate administration','Understand the stages of probate and the value of early guidance.','succession'),('Property','Property transactions begin with verification','Why careful searches and review matter before commitments are made.','property')]
def insight_cards():
 out=''
 for i,(t,h,d,s) in enumerate(insights):out+=f'<a class="insight-card" href="/insights#{s}"><span class="insight-no">0{i+1}</span><span class="insight-tag">{t}</span><h3>{h}</h3><p>{d}</p><span class="text-link">Read insight {icon("arrow-up",size=17)}</span></a>'
 return out

def contact_form():
 return f'''<form class="enquiry-form" data-contact-form><div class="form-grid"><label>Full name <input name="name" autocomplete="name" placeholder="Your full name" required maxlength="120"></label><label>Email address <input name="email" type="email" autocomplete="email" placeholder="you@example.com" required maxlength="180"></label></div><div class="form-grid"><label>Phone (optional) <input name="phone" type="tel" autocomplete="tel" placeholder="07XX XXX XXX" maxlength="30"></label><label>Area of assistance <select name="matter" required><option value="" disabled selected>Select a practice area</option><option>Mediation / ADR</option><option>Succession / Probate</option><option>Property / Conveyancing</option><option>Commercial / Corporate</option><option>Data Protection / IP</option><option>Litigation / Legal Advisory</option><option>Other legal enquiry</option></select></label></div><label>Brief message <textarea name="message" rows="5" placeholder="Please share a brief, non-confidential outline of your enquiry." required maxlength="3500"></textarea></label><p class="form-note">This form opens your email application with a prepared enquiry; it does not send information directly from this website. Please avoid including sensitive details before the firm confirms it can assist.</p><button type="submit" class="btn btn-primary">Prepare email enquiry {icon('arrow-up',size=18)}</button><p class="form-feedback" role="status" aria-live="polite" hidden></p></form>'''

home=f'''
<section class="reference-hero"><div class="reference-hero-inner"><span class="reference-kicker">JOYCE NDEHI &amp; COMPANY ADVOCATES · KIAMBU</span><h1>Committed to Upholding <em>Justice.</em></h1><p>Trusted legal guidance for individuals, families and businesses. Professional representation, clear advice and practical solutions.</p><div class="reference-hero-actions">{link('Request a Consultation','/contact','btn btn-primary')}{link('Explore Our Services','/practice-areas','btn btn-cream')}</div></div><span class="reference-hero-scroll">SCROLL TO DISCOVER <span aria-hidden="true">↓</span></span></section>
<section class="trust-strip"><div class="container trust-inner"><span>Practical legal guidance</span><span aria-hidden="true" class="trust-dot"></span><span>Personal &amp; business matters</span><span aria-hidden="true" class="trust-dot"></span><span>Mediation &amp; dispute resolution</span><span aria-hidden="true" class="trust-dot"></span><span>Kiambu Town, Kenya</span></div></section>
<section class="section reference-about" id="about-us"><div class="container"><div class="reference-heading">{eyebrow('WELCOME TO OUR FIRM')}<h2>About <em>Joyce Ndehi &amp; Company Advocates</em></h2><span class="reference-rule"></span></div><div class="reference-about-grid"><div class="reference-about-photo"><img src="/assets/media/joyce-ndehi.webp" alt="Joyce Ndehi, Advocate of the High Court of Kenya" loading="lazy"></div><div class="reference-about-text"><span class="eyebrow">YOUR TRUSTED LEGAL PARTNER IN KIAMBU</span><h3>Dedicated legal counsel. Personal attention.</h3><p class="body-large">Joyce Ndehi &amp; Company Advocates provides professional legal guidance for individuals, families and businesses in Kiambu and beyond.</p><p>We offer counsel and representation in mediation, succession and probate, property transactions, commercial matters, data protection, and dispute resolution. We listen carefully, explain your options clearly, and work towards practical outcomes.</p><blockquote>“Every legal matter deserves thoughtful attention and a clear way forward.”</blockquote><span class="reference-signature">Joyce Ndehi <small>ADVOCATE OF THE HIGH COURT OF KENYA</small></span>{link('More About Our Firm','/about','btn btn-primary')}</div></div></div></section>
<section class="reference-values"><div class="reference-values-overlay"></div><div class="container reference-values-content"><div class="reference-heading reference-heading-light">{eyebrow('OUR GUIDING PRINCIPLES',True)}<h2>Our Vision, Mission &amp; Promise</h2><span class="reference-rule"></span></div><div class="reference-values-grid"><article><span class="reference-value-icon">{icon('spark',size=38)}</span><h3>Our Vision</h3><p>To make legal guidance accessible, understandable and useful to the people and businesses who need it.</p></article><article><span class="reference-value-icon">{icon('balance',size=38)}</span><h3>Our Mission</h3><p>To provide thoughtful legal representation through honest communication, careful preparation and practical advice.</p></article><article><span class="reference-value-icon">{icon('shield',size=38)}</span><h3>Our Promise</h3><p>To serve every client with professionalism, integrity and respect while pursuing the best available legal options.</p></article></div></div></section>
<section class="section services-section"><div class="container">{section_header('WHAT WE DO','Our Areas of <em>Specialization.</em>','A range of services to help you make informed decisions and address legal challenges.',link('All practice areas','/practice-areas','text-link arrow-link'))}<div class="service-grid">{service_cards()}</div></div></section>
<section class="feature-band"><div class="feature-image"><img src="/assets/media/joyce-mediation.webp" width="1536" height="1024" alt="Joyce Ndehi attending mediation and certification training" loading="lazy"><span class="photo-caption">MEDIATION &amp; ALTERNATIVE DISPUTE RESOLUTION</span></div><div class="feature-content"><span class="eyebrow eyebrow-light">A CONSTRUCTIVE APPROACH</span><h2>Not every disagreement needs a courtroom.</h2><p>Mediation offers a structured, confidential setting for parties to work through disputes and consider mutually acceptable outcomes. Where appropriate, it can be a meaningful step before litigation.</p>{link('Explore mediation','/practice-areas#mediation','btn btn-cream')}</div></section>
<section class="section why-section"><div class="container">{section_header('WHY WORK WITH US','The details make <em>the difference.</em>')}<div class="why-grid"><article><span>01</span><h3>A considered approach</h3><p>Attention to the facts and documents behind every legal question.</p></article><article><span>02</span><h3>Direct communication</h3><p>Clear explanations of your options and the practical next steps.</p></article><article><span>03</span><h3>Resolution-focused</h3><p>Negotiation and mediation considered alongside formal legal routes.</p></article><article><span>04</span><h3>Broad perspective</h3><p>Support across personal, property, commercial and dispute matters.</p></article></div></div></section>
<section class="founder-section"><div class="container founder-grid"><div class="founder-statement">{eyebrow('MEET OUR ADVOCATE',True)}<h2>Legal advice should make the path ahead <em>clearer.</em></h2><div class="founder-mark">JN <span>/</span></div></div><div class="founder-detail"><span>ADVOCATE OF THE HIGH COURT OF KENYA</span><h3>Joyce Ndehi</h3><p>Joyce leads the practice, bringing a legal perspective spanning civil and commercial law, probate and administration, conveyancing, legal drafting, trial advocacy and related advisory work.</p>{link('Meet Joyce Ndehi','/managing-partner','text-link text-link-light')}</div></div></section>
<section class="section insights-section"><div class="container">{section_header('FROM OUR JOURNAL','Perspectives worth <em>considering.</em>','Straightforward introductory guidance on common legal questions.',link('View all insights','/insights','text-link arrow-link'))}<div class="insight-grid">{insight_cards()}</div></div></section>
<section class="contact-panel-section"><div class="container contact-panel"><div>{eyebrow('HERE WHEN YOU NEED GUIDANCE')}<h2>Your legal matter deserves <em>a clear first step.</em></h2><p>Reach our Kiambu Town office by phone, WhatsApp or email. Share a brief outline and we can discuss what comes next.</p><div class="contact-inline"><a href="tel:+254706806549">{icon('phone',size=19)} {phone}</a><a href="mailto:{email}">{icon('mail',size=19)} {email}</a></div></div>{link('Start a conversation','/contact','btn btn-primary')}</div></section>'''
(r/'index.html').write_text(wrap('Joyce Ndehi & Company Advocates | Legal Counsel in Kiambu','Joyce Ndehi & Company Advocates offers mediation, succession, conveyancing, commercial and dispute-resolution legal services from Kiambu Town, Kenya.',home,'/'))


def page_hero(ey,title,desc):return f'<section class="inner-hero"><div class="container inner-hero-inner">{eyebrow(ey)}<h1>{title}</h1><p>{desc}</p><div class="inner-hero-line" aria-hidden="true"></div></div></section>'
about=page_hero('ABOUT THE FIRM','Counsel that sees <em>the whole picture.</em>','Practical, people-centred legal support from the heart of Kiambu Town.')+f'''
<section class="section"><div class="container about-layout"><div class="about-primary">{eyebrow('WHO WE ARE')}<h2>A practice built around <em>understanding.</em></h2><p class="body-large">Joyce Ndehi &amp; Company Advocates is based at Telcom Exchange House on Biashara Street, Kiambu Town. We support individuals, families and businesses across personal, property and commercial legal matters.</p><p>Our services combine advisory, transactional and dispute-resolution work, including mediation, succession, conveyancing, commercial law, data protection, intellectual property and litigation.</p><p>We place particular emphasis on helping parties approach conflicts constructively where mediation or negotiation may be suitable, while remaining available for more formal legal processes when required.</p>{link('Discuss your matter','/contact','btn btn-primary')}</div><aside class="about-location"><span>OUR HOME</span>{icon('location',size=44)}<h3>Rooted in Kiambu.<br>Focused on you.</h3><p>Telcom Exchange House<br>Biashara Street, 1st Floor<br>Kiambu Town, Kenya</p><a class="text-link" href="/contact">Find our office {icon('arrow-up',size=17)}</a></aside></div></section>
<section class="section values-section"><div class="container">{section_header('OUR VALUES','How we approach <em>your matter.</em>')}<div class="values-grid"><article class="value-card"><span class="value-number">01 — CLARITY</span>{icon('book',size=35)}<h3>Clear guidance</h3><p>Making the legal position and your options easier to understand.</p></article><article class="value-card"><span class="value-number">02 — RESOLUTION</span>{icon('balance',size=35)}<h3>Constructive thinking</h3><p>Considering dialogue and mediation alongside other lawful remedies.</p></article><article class="value-card"><span class="value-number">03 — CARE</span>{icon('check',size=35)}<h3>Attentive service</h3><p>Treating the facts, people and consequences of each matter seriously.</p></article></div></div></section>
<section class="section"><div class="container about-ending"><div>{eyebrow('OUR WORK')}<h2>Legal support that meets you <em>where you are.</em></h2></div><div><p>Whether you are preparing a property transaction, navigating an estate, reviewing a business agreement or seeking a way to settle a dispute, we aim to help you approach the decision with confidence.</p>{link('Explore our services','/practice-areas','btn btn-primary')}</div></div></section>'''
(r/'about.html').write_text(wrap('About Us | Joyce Ndehi & Company Advocates','Get to know Joyce Ndehi & Company Advocates, a Kiambu Town law practice focused on clear counsel, mediation and legal solutions.',about,'/about','about'))

practice=page_hero('OUR SERVICES','Legal expertise with <em>a practical purpose.</em>','From important personal decisions to complex business and property matters, find the support you need.')+f'<section class="section services-detail-section"><div class="container">{section_header("PRACTICE AREAS","A thoughtful approach to <em>each challenge.</em>","Specific advice depends on the circumstances and documents involved.")}<div class="practice-detail-list">'
long_descriptions=[
 ('Structured and confidential dispute-resolution support, including family, succession, commercial, workplace and property disagreements. We explore whether mediation or negotiation can provide a suitable route forward.', ['Mediation & negotiated settlement','Family and succession disputes','Workplace and commercial disagreements']),
 ('Advice and assistance on wills, grants of probate and letters of administration, the administration and distribution of estates, and disagreements arising in succession matters.', ['Wills and estate planning','Probate and administration','Succession-related disputes']),
 ('Legal assistance with property transactions, due diligence, agreements, transfers, ownership issues and disputes relating to land and property.', ['Property searches and due diligence','Sale and transfer documents','Land and ownership questions']),
 ('Practical advice for commercial transactions, contractual arrangements, corporate legal questions and tax-related advisory matters.', ['Business and commercial contracts','Corporate advisory','Tax-related legal issues']),
 ('Guidance on obligations concerning personal data and intellectual-property rights, including copyright and related concerns affecting organisations and creators.', ['Data-protection compliance','Copyright and creative rights','Intellectual-property advisory']),
 ('Legal analysis, strategy, drafting, negotiations and representation when a dispute or other issue requires more formal action or legal advice.', ['Case assessment and legal strategy','Drafting and negotiations','Litigation and representation'])]
for (s,n,title,subtitle,i,desc),(detail,points) in zip(services,long_descriptions):
 practice+=f'<article id="{s}" class="practice-detail"><div class="practice-detail-num">{n}<span>/06</span></div><div class="practice-detail-main"><span class="practice-detail-icon">{icon(i,size=32)}</span><h3>{title}</h3><p class="practice-subtitle">{subtitle}</p><p>{detail}</p><div class="practice-pills">'+''.join(f'<span>{p}</span>' for p in points)+f'</div></div><div class="practice-detail-action">{link("Enquire about this area",f"/contact?matter={s}","text-link arrow-link")}</div></article>'
practice+='</div></div></section>'
(r/'practice-areas.html').write_text(wrap('Practice Areas | Joyce Ndehi & Company Advocates','Explore legal services in mediation, succession, property and conveyancing, corporate law, data protection and litigation in Kiambu.',practice,'/practice-areas','practice-areas'))

partner=page_hero('OUR ADVOCATE','Experience, attention <em>and perspective.</em>','Get to know the advocate behind the practice.')+f'''
<section class="section"><div class="container profile-grid"><div class="profile-portrait"><img src="/assets/media/joyce-ndehi.webp" width="1254" height="1254" alt="Portrait of Joyce Ndehi, Advocate of the High Court of Kenya"><div class="profile-caption"><strong>Joyce Ndehi</strong><span>ADVOCATE &amp; FOUNDER</span></div></div><div class="profile-copy">{eyebrow('JOYCE NDEHI')}<h2>Legal counsel with <em>an eye for resolution.</em></h2><p class="body-large">Joyce Ndehi is an Advocate of the High Court of Kenya and leads Joyce Ndehi &amp; Company Advocates in Kiambu Town.</p><p>Her public professional profile identifies training and experience across civil and commercial law, probate and administration, conveyancing, legal writing, criminal law and trial advocacy.</p><p>Her listed advisory areas also include tax and copyright, while the firm's client materials place emphasis on mediation, succession and practical legal support.</p><div class="profile-note"><span>AREAS OF FOCUS</span><p>Mediation · Succession · Property · Commercial Matters · Dispute Resolution</p></div>{link('Get in touch','/contact','btn btn-primary')}</div></div></section>'''
(r/'managing-partner.html').write_text(wrap('Meet Joyce Ndehi | Joyce Ndehi & Company Advocates','Meet Joyce Ndehi, Advocate of the High Court of Kenya and founder of Joyce Ndehi & Company Advocates in Kiambu Town.',partner,'/managing-partner','managing-partner'))

articles=[('mediation','MEDIATION & ADR','When mediation may be worth considering','Mediation offers parties a confidential process for discussing a dispute with the assistance of a neutral mediator. It can be relevant in family, succession, property, workplace, commercial and other civil disputes where the parties are able to explore a negotiated outcome.'),('succession','SUCCESSION','Succession planning and estate administration','Wills, probate or letters of administration, identifying estate assets and beneficiaries, and the eventual distribution of an estate involve distinct legal steps. Early advice can help families understand the process before disagreements arise.'),('property','PROPERTY','Property transactions begin with verification','Conveyancing involves more than signing an agreement. Searches, ownership information, transaction documents, consents and completion steps should be reviewed carefully before parties commit funds or transfer interests.'),('data','DATA PROTECTION','Data protection is a governance issue','Organisations that collect or use personal information should understand the legal basis for processing, the information they hold and the safeguards expected when managing it.')]
insights=page_hero('LEGAL INSIGHTS','A little more clarity <em>goes a long way.</em>','Introductory perspectives on important legal questions. These articles are general information, not advice for a specific matter.')+'<section class="section"><div class="container"><div class="article-list">'
for i,(slug,topic,title,desc) in enumerate(articles):insights+=f'<article class="article-row" id="{slug}"><div class="article-side"><span class="article-count">0{i+1}</span><span class="article-topic">{topic}</span></div><div><h2>{title}</h2><p>{desc}</p><a href="/contact" class="text-link arrow-link">Discuss a related question {icon("arrow-up",size=17)}</a></div></article>'
insights+='</div><div class="disclaimer">The information above is general in nature. Legal advice depends on the facts and circumstances of a particular matter.</div></div></section>'
(r/'insights.html').write_text(wrap('Legal Insights | Joyce Ndehi & Company Advocates','Read introductory legal guidance on mediation, succession, property transactions and data protection from Joyce Ndehi & Company Advocates.',insights,'/insights','insights'))

contact=page_hero('CONTACT OUR OFFICE','Let’s talk about <em>what comes next.</em>','You can reach the firm directly by phone, WhatsApp or email, or prepare a brief enquiry below.')+f'''
<section class="section"><div class="container contact-grid"><div class="contact-information">{eyebrow('GET IN TOUCH')}<h2>We’re here to <em>listen.</em></h2><p>Tell us a little about your matter, and we can discuss the appropriate next step.</p><div class="contact-method"><span>{icon('phone',size=23)}</span><div><small>CALL THE FIRM</small><a href="tel:+254706806549">{phone}</a></div></div><div class="contact-method"><span>{icon('mail',size=23)}</span><div><small>EMAIL</small><a href="mailto:{email}">{email}</a></div></div><div class="contact-method"><span>{icon('location',size=23)}</span><div><small>VISIT US</small><p>Telcom Exchange House<br>Biashara Street, 1st Floor<br>Kiambu Town, Kenya</p></div></div>{link('Message us on WhatsApp',wa,'btn btn-outline',key='whatsapp',extra='target="_blank" rel="noopener noreferrer"')}</div><div class="form-shell">{eyebrow('SEND AN ENQUIRY')}<h3>Prepare your message</h3><p>Fill in the details below and your email application will open with the message ready to send.</p>{contact_form()}</div></div></section>
<section class="location-section"><div class="container">{section_header('VISIT OUR OFFICE','Find us in <em>Kiambu Town.</em>','Telcom Exchange House, Biashara Street, 1st Floor, Kiambu Town, Kenya.')}<div class="map-shell"><div class="map-visual"><iframe title="Interactive street map of central Kiambu Town, near Biashara Street" src="https://www.openstreetmap.org/export/embed.html?bbox=36.825%2C-1.180%2C36.846%2C-1.160&amp;layer=mapnik" loading="lazy" referrerpolicy="strict-origin-when-cross-origin"></iframe><div class="map-visual-footer"><span>Kiambu Town area map · <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener noreferrer">© OpenStreetMap contributors</a> · exact pin pending verification</span><a href="https://www.google.com/maps/search/?api=1&amp;query=Telcom%20Exchange%20House%20Biashara%20Street%20Kiambu%20Town%20Kenya" target="_blank" rel="noopener noreferrer">Open Google Maps ↗</a></div></div><div class="map-address"><span>OUR LOCATION</span><h3>Telcom Exchange House</h3><p>Biashara Street, 1st Floor<br>Kiambu Town, Kenya</p>{link('Open directions','https://www.google.com/maps/dir/?api=1&destination=Telcom+Exchange+House+Biashara+Street+Kiambu+Town+Kenya','text-link arrow-link',extra='target="_blank" rel="noopener noreferrer"')}</div></div></div></section>'''
(r/'contact.html').write_text(wrap('Contact Us | Joyce Ndehi & Company Advocates','Contact Joyce Ndehi & Company Advocates in Kiambu Town. Call 0706 806 549, WhatsApp or email joycendehiadvocates@gmail.com.',contact,'/contact','contact'))

for slug,title,text in [('privacy','Privacy','This website does not intentionally store contact-form submissions. The enquiry form opens your own email application rather than submitting data to the website. If you contact the firm directly, information you provide may be used to respond to your enquiry and assess whether the firm can assist. Please avoid sending confidential or urgent information until the firm has confirmed it can act for you.'),('terms','Website Terms','Information on this website is general and does not replace advice based on the facts of a specific matter. Viewing this website or contacting the firm does not itself create an advocate-client relationship. Practice descriptions are summaries for website presentation and do not guarantee the firm can accept any particular instruction.')]:
 body=page_hero('WEBSITE INFORMATION',title+'.','Important information about using this website.')+f'<section class="section"><div class="container policy-body"><h2>{title}</h2><p>{text}</p>{link("Contact our office","/contact","btn btn-primary")}</div></section>'
 (r/f'{slug}.html').write_text(wrap(f'{title} | {name}',text[:155],body,'',slug))
for status,title,message in [('404','Page not found','The page you are looking for may have moved or no longer exists.'),('500','Something went wrong','We encountered an unexpected problem. Please try again.'),('503','Temporarily unavailable','The site is temporarily unavailable. You can still contact the firm directly.'),('504','Request timed out','That request took longer than expected. Please try again.')]:
 body=f'<section class="error-page"><div class="container">{eyebrow(status)}<h1>{title}<span>.</span></h1><p>{message}</p>{link("Return home","/","btn btn-primary")} {link("Contact the firm","/contact","btn btn-outline")}</div></section>'
 (r/f'{status}.html').write_text(wrap(f'{status} | {name}',message,body))
print('Generated',len(list(r.glob('*.html'))),'HTML pages')
